### ISSUE TITLE
Add the SCMConnector.bat and SCMConnector.sh files

### ISSUE THREAD

**Issue by sschuberth** [blackducksoftware/scmconnector#3]
Please add the platform-specific startup scripts from the binary distribution so we can also make fixes to these.

**Comment by stevebillings** [comment]
Those are actually generated via the appassembler-maven-plugin, configured in pom.xml. See http://www.mojohaus.org/appassembler/appassembler-maven-plugin/. Via the configuration in pom.xml you have control over some things, like JVM arguments.

**Comment by stevebillings** [comment]
What change are you looking to make?

**Comment by sschuberth** [comment]
Ah, I see. If the files are generated they should of course not be committed. The problem is with the _classpath_ being too long on Windows if the installation path is long, as each _jar_ from the _lib_ directory is added individually. While the issue is documented in the _README_, there's no need for that as since Java 1.6 the _classpath_ [can contain wildcards](http://stackoverflow.com/a/219801/1127485). Using such a wildcard fixes running the script from a long installation path for me.

Looking at the appassembler docs the proper way to fix this probably is to use [useWildcardClassPath](http://www.mojohaus.org/appassembler/appassembler-maven-plugin/assemble-mojo.html#useWildcardClassPath), assuming that you do not need to support Java versions below 1.6.

**Comment by stevebillings** [comment]
We should definitely be using that... thanks for pointing it out. I will plan on making that change within a day or two, though I'm not sure at this point when the next release will be. What's the urgency (of getting a release with this change) for you?

**Comment by sschuberth** [comment]
It's not urgent for me to get a release, I've already patched the file locally. But thanks for asking.

**Comment by stevebillings** [comment]
Have added the maven assembler plugin option useWildcardClassPath in the pom.xml.
