### ISSUE TITLE
Fix build failure due to missing dependency

### ISSUE THREAD

**Issue by sschuberth** [blackducksoftware/scmconnector#4]
It seems the `protex-plugin-integration:jar:1.1-SNAPSHOT` artifact as introduced in f0390a10585f086fa7d34e1a9db1cafca991a5cd is not published to JCenter. Hence the build does not work out of the box. I'd suggest to either publish the `SNAPSHOT` artifact, or revert to version 1.0.7 in the `master` branch.

To prevent things like this in the future, it's probably a good idea to integrate with [Travis CI](https://travis-ci.org/) and put a build badge into the [README](https://github.com/blackducksoftware/scmconnector/blob/master/README.md).

**Comment by stavvy-akamen** [comment]
Sebastian,

JCenter does not allow for SNAPSHOT builds, because there are so many moving pieces Travis CI may be an option.  We have been looking at that, but have not gotten around to implementing a solution just yet.

**Comment by sschuberth** [comment]
From read [this article](https://www.jfrog.com/confluence/display/RTF/Deploying+Snapshots+to+oss.jfrog.org) it seems you could publish SNAPSHOT artifacts to https://oss.jfrog.org/ and later promote them to JCenter. In any case Travis CI integration would be great, as well as making some guarantees on the _master_ branch being always stable.

**Comment by stavvy-akamen** [comment]
Thanks for the prompt feedback.  Indeed OSS Jfgrog was floated as an intermediate solution but complications arose during the automation phase of it.

We are experiencing challenges because we have a blend of open sourced libraries and behind the scenes closed infrastructure.

However your feedback is essential in making sure these libraries are useful for everyone outside of Black Duck.

**Comment by stevebillings** [comment]
Regarding the more tactical issue: That pom change was a temporary experiment that I later accidentally checked in. I just need to get past one test failure (that I suspect is a red herring), and I'll have the pom change (back to protex-plugin-integration:jar:1.0.7) checked in.

**Comment by sschuberth** [comment]
That sounds great :+1:

**Comment by stevebillings** [comment]
Changed protex-plugin-integration:jar version in pom.xml back to 1.0.7, which it should have been all along. Sorry about the mistake!

**Comment by sschuberth** [comment]
Thanks, I can confirm that it builds now. I'm getting some test failures, but that's a different story I'll look into later.
