### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by vcmgc27** [blackducksoftware/scmconnector#9]
Hello Ari Kamen,

Discussion on the issue raised: https://github.com/blackducksoftware/scmconnector/issues/8

Guess you haven't seenthe above issue properly. I haven't modified any code or any jar file from this scmconnector package. Just downloaded the package and added information to config.properties file and ran the command as mentioned in documentation section.

Please understand, no code or binaries modified in this package. Using as it is out of box.

Thanks,
Gowtham C

**Comment by vcmgc27** [comment]
I tried out the package once again. By adding 7.5.0 jar. it worked.

Thanks,
Gowtham C

**Comment by vcmgc27** [comment]
Hi,

First time the script works and sends mail. If there is a delta scan (second time) is running, script is executing but not sending mail. Getting this error

05-Apr-2017 07:41:54	2017-04-05 07:41:54,040 ERROR (main) [com.blackducksoftware.tools.commonframework.standard.email.CFEmailNotifier] - Problem parsing template: Error converting template file to string, cannot send emails

Note: No code or binary changed or customized. executed script as it is.

Thanks,
Gowtham C

**Comment by stavvy-akamen** [comment]
I am glad you got the dependency figured out!  Good to hear. 
Not sure about the second problem, looks like a bug on our end. 

Unfortunately this is no longer a supported plugin, but we will happily accept all commits!

Thanks.
